Ваше ФИО, номер группы

## Задание №1

1. Прежде чем заполнять пропуски, их нужно найти. Напечатайте на экране строки таблицы, у которых есть пропуски в столбце `'faculty_name'`. Данные находятся в файле `hogwarts_points.csv`.

In [113]:
import pandas as pd

# Аргумент sep нужен для указания символа разделителя в файле данных. По умолчанию это ,
# Но бывают и дургие разделители, например ;
hog = pd.read_csv('hogwarts_points.csv', sep=';')

hog

   id faculty_name      student_name  points
0   0   Гриффиндор      Гарри Поттер      15
1   1     Слизерин      Драко Малфой      28
2   2    Когтевран    Полумна Лавгуд      10
3   3          NaN         Рон Уизли       5
4   4    Пуффендуй    Седрик Диггори      17
5   5   Гриффиндор  Невилл Долгопупс      12

2. Восстановите справедливость: верните Рону его факультет, заменив значение `NaN` на `'Гриффиндор'` методом `fillna()`. Выведите на экран таблицу `hogwarts_points`. Данные находятся в файле `hogwarts_points.csv`.

In [114]:
hog = hog.fillna('Гриффиндор')

hog

   id faculty_name      student_name  points
0   0   Гриффиндор      Гарри Поттер      15
1   1     Слизерин      Драко Малфой      28
2   2    Когтевран    Полумна Лавгуд      10
3   3   Гриффиндор         Рон Уизли       5
4   4    Пуффендуй    Седрик Диггори      17
5   5   Гриффиндор  Невилл Долгопупс      12

3. Найдите суммарные баллы каждого из факультетов и сохраните результат в переменной `faculty_points`. Потом используя эту переменную найдите факультет-победитель и сохраните результат в переменной `winner`. В конце выведите значения обеих переменных на экран. Данные находятся в файле `hogwarts_points.csv`.

In [115]:
faculty_point = hog.groupby('faculty_name')['points'].sum()

winner = hog.groupby('faculty_name')['points'].sum().idxmax()

print(faculty_point)

print()

print(winner)

faculty_name
Гриффиндор    32
Когтевран     10
Пуффендуй     17
Слизерин      28
Name: points, dtype: int64

Гриффиндор

4. Применим полученные в Хогвартсе знания к реальной задаче. Возьмём источники трафика Яндекс.Маркета и рассчитаем конверсию.
Найдите количество визитов из каждого источника трафика. Для этого сгруппируйте данные из столбца с идентификаторами пользователей по столбцу с источниками. Результат сохраните в переменной `visits` и выведите на экран. Данные находятся в файле `logs.csv`.

In [116]:
df = pd.read_csv('logs.csv')
visit_source = df.groupby('source')['user_id'].sum()

visit_source

source
context    259897921912221
email       61778698940554
other      666962903951240
undef         866825644888
Name: user_id, dtype: int64

5. Посчитайте количество совершённых покупок для каждого источника трафика. Результат сохраните в переменной `purchase` и выведите на экран. Данные находятся в файле `logs.csv`.

In [117]:
df = pd.read_csv('logs.csv')
purchase = df.groupby('source')['purchase'].sum()

purchase

source
context    3029
email       913
other      8041
undef        12
Name: purchase, dtype: int64

6. Посчитайте конверсию по каждому источнику трафика, результат сохраните в переменной `conversion` и выведите на экран. Данные находятся в файле `logs.csv`.

In [118]:
df = pd.read_csv('logs.csv')
convertion = df.groupby('source')['purchase'].mean()

convertion

source
context    0.058214
email      0.074355
other      0.060082
undef      0.066298
Name: purchase, dtype: float64

## Задание №2

1. Перед вами фрагмент датафрейма HR-команды небольшой компании.

In [119]:
Фамилия Возраст Роль        Город проживания Команда           Накопленные дни отпуска
Игнатьев   42   разработчик Москва           бэкэнд-разработка       5
Макаров    30   аналитик    Москва           аналитика               2
Черняев    31   разработчик Екатеринбург     мобильная разработка    7
Оборицкая  28   менеджер    Пермь            бэкэнд-разработка       0
Кац        29   аналитик    Москва           маркетинг               1
Игнатьев   35   менеджер    Санкт-Петербург  мобильная разработка    6
Троицкая   29   разработчик Нижний Новгород  фронтенд разработка     14
Айнетдинов 25   копирайтер  Пермь            маркетинг               12

SyntaxError: invalid syntax (991525768.py, line 1)

Какие из этих переменных — категориальные?

- Фамилия

- Возраст

- Роль

- Город проживания

- Команда

- Накопленные дни отпуска

Помните, что логические значения тоже относятся к категориальным.

Ответ: Фамилия, Роль, Город Проживания, Команда

2. Перед вами датафрейм сервиса бронирования личного жилья для отдыха, который хранит информацию о жилье.

In [ ]:
UID (Уникальный ID)                  Город            Индекс Количество гостей Количество ванных комнат Количество спален Количество кроватей Стоимость
0ebb48f9-9b38-4d32-808b-a98d796614d5 Великий Новгород 173008          1                 1                        1                 1          1000
0d5120e1-4388-4c17-95e0-67ce218e407a Сочи             354065          3                 1                        2                 2          3500
e7b66f50-afca-487a-afeb-72ff58ea5754 Псков            180020          2                 1                        1                 1          1200
8c4a66bc-4bb0-4d1e-b0bb-6b5b3d928273 Владивосток      690034          5                 2                        3                 3          7000
4d453942-1757-4c82-bf84-f26adefbc9c6 Москва           107078          2                 1                        2                 2          4000

Какие из переменных являются количественными?

- UID

- Город

- Индекс

- Количество гостей

- Количество ванных комнат

- Количество спален

- Количество кроватей

- Стоимость

Ответ: Количество гостей
Количество ванных комнат
Количество спален
Количество кроватей
Стоимость

3. Перед вами датафрейм товаров Яндекс Маркета.

In [ ]:
Название                                                   Количество отзывов Производитель Минимальная цена Максимальная цена   Категория                   Цвет  Скидка
Холодильник ATLANT ХМ 4208-000                                      516           ATLANT         19460             29999       Холодильники                  Белый  true
23.8" Монитор PRO MP242P, 1920x1080, 75 Гц, IPS                     0             Xiaomi         16890             39480          Мониторы                   Чёрный false
Фильтр под мойкой БАРЬЕР ЭКСПЕРТ Жесткость x2 белый Н291Р01         55            БАРЬЕР         4348              5052        Фильтры и умягчители для воды Белый  false
Мука пшеничная С.Пудовъ, второй сорт, 1 кг                          31            С.Пудовъ        48               48          Мука пшеничная                Белый  false
34" Монитор Xiaomi Mi Curved Gaming, 3440x1440, 144 Гц, *VA, black  544           Xiaomi         36990             45990          Мониторы                   Чёрный  true

Какие из переменных являются категориальными?

- Количество отзывов

- Производитель

- Минимальная цена

- Максимальная цена

- Категория

- Цвет

- Скидка

Ответ: Производитель, Категория, Цвет

4. Краудфандинговый сервис хранит информацию о проектах. Изучите датафрейм и определите к какому типу относится каждая переменная.

In [ ]:
Категория           Цель       Собрано    Статус       Поддержавшие
Благотворительность 320 000    295 750    Идёт сбор    121
Экология и природа  1 000 000  1 200 000  Сбор закрыт  938
Обучение            500 000    11 080     Идёт сбор    10
Музыка              240 000    0          Идёт сбор    0
Обучение            450 000    400 000    Сбор закрыт  204

Напишите какие переменные к какой категории относятся.

Ответ: 
Качественные: Категория, статус
Колличественные: Цель, Собрано, Поддержавшие

## Задание №3

1. Извлеките из таблицы строки с информацией о разработчиках (Маша, Вася, Настя) и напечатайте их на экране. Для этого в атрибут `loc` передайте список значений `True` и `False`.
Чтобы можно было точнее проверить ваше решение, сохраните список значений `True` и `False` в переменной `rows`. Данные находятся в файле `projects.csv`.

In [123]:
df = pd.read_csv('projects.csv', sep = ';')
rows = [True, False, True, False, False, False, True, False]
df.loc[rows]

     Имя         Роль Новая функция Экперимент Статья
0   Маша  разработчик             +        NaN    NaN
2   Вася  разработчик           NaN          +      +
6  Настя  разработчик             +          +      -

2. Напишите выражение со следующим условием для строк: роль члена команды — разработчик. Сохраните результат этого выражения в переменную `rows` и напечатайте её на экране. Данные находятся в файле `projects.csv`.

In [126]:
df = pd.read_csv('projects.csv', sep = ';')

rows = df['Роль'] == 'разработчик'

df.loc[rows]

     Имя         Роль Новая функция Экперимент Статья
0   Маша  разработчик             +        NaN    NaN
2   Вася  разработчик           NaN          +      +
6  Настя  разработчик             +          +      -

3. Напишите логическое выражение, проверяющее, что член команды не менеджер. Сохраните результат этого выражения в переменной rows и напечатайте его на экране. Данные находятся в файле `projects.csv`.

In [128]:
df = pd.read_csv('projects.csv', sep = ';')

rows = df['Роль'] != 'менеджер'

df.loc[rows]

     Имя         Роль Новая функция Экперимент Статья
0   Маша  разработчик             +        NaN    NaN
1   Петя     аналитик             +          -      -
2   Вася  разработчик           NaN          +      +
4   Ваня     аналитик           NaN          +    NaN
6  Настя  разработчик             +          +      -
7   Лена   копирайтер           NaN        NaN      +

4. Давайте заполним пропуски в столбце проекта с новой функцией. Для этого замените все значения, не равные плюсу, на минусы. Тогда пропуски заменятся на минусы, и сами минусы заменятся на минусы (то есть не поменяются). После замены выведите на экран всю полученную таблицу.
Отдельную переменную для списка значений `True` и `False` можно не создавать.

5. Найдите всех членов команды, которые одновременно занимаются экспериментом и работают над статьей. Напечатайте на экране соответствующие строки таблицы. Для этого примените атрибут loc и выражение с условием на значение столбца.

## Заадние №4

1. Прочитайте данные из файла metrica_data.csv. Результат сохраните в переменной metrica. Посчитайте средний возраст пользователей и сохраните его в переменной `age_avg`. Выведите результат на экран.

2. Замените пропущенные значения в столбце `age` на средний возраст. Выведите на экран первые 10 строк набора данных.

3. Найдите среднее время просмотра сайта и сохраните в переменной `time_avg`. Выведите результат на экран.

4. Можно заменить время на среднее значение. Однако пользователи заходят в интернет то с мобильного устройства, то с компьютера. Учтём этот факт для повышения точности заполнения пропущенных данных о времени на сайте.
Выберите строки таблицы с данными о просмотрах с компьютера, т.е. такие, где в столбце 'device_type' указано значение 'desktop'. Сохраните результат в переменной desktop_data и выведите первые 5 строк на экран.

5. Установите, сколько времени в среднем проводят на сайте пользователи настольных компьютеров. Результат сохраните в переменной desktop_data_time_avg. Закомментируйте вывод предыдущего задания и выведите значение desktop_data_time_avg на экран.

6. Получите таблицу с данными о просмотрах с мобильных платформ. Сохраните результат в переменной mobile_data и выведите первые 5 строк на экран.

7. Посчитайте среднее время пребывания на сайте пользователей мобильных платформ. Результат сохраните в переменной mobile_data_time_avg. Закомментируйте вывод предыдущего задания и выведите значение mobile_data_time_avg на экран.