### Задание 1: Преобразование строковых дат в даты
**Задача:** Преобразовать столбец дат в строковом формате (YYYY-MM-DD) в объекты времени в Pandas.

**Набор данных:** Данные о продажах (`sales_data.csv`) со столбцами для идентификатора продажи, продукта и даты продажи (в строковом формате).

**Задачи:**

1. Загрузите набор данных в Pandas DataFrame.
2. Преобразуйте столбец "Дата продажи" из строкового формата в объект datetime.
3. Извлеките год, месяц и день в виде отдельных столбцов.
4. отфильтруйте набор данных, чтобы включить в него только продажи за текущий год.

In [9]:
import pandas as pd

df = pd.read_csv("sales_data.csv")
df['Sale Date'] = df['Sale Date'].astype('datetime64[s]')
df['Year'] = df['Sale Date'].dt.year
df['Month'] = df['Sale Date'].dt.month
df['Day'] = df['Sale Date'].dt.day

df_sort = df[df['Year'] >= 2024]
df_sort

    Sale ID    Product  Sale Date  Year  Month  Day
10       11  Product A 2024-01-11  2024      1   11
11       12  Product A 2024-01-12  2024      1   12
12       13  Product C 2024-01-13  2024      1   13
13       14  Product B 2024-01-14  2024      1   14
14       15  Product C 2024-01-15  2024      1   15
15       16  Product B 2024-01-16  2024      1   16
16       17  Product B 2024-01-17  2024      1   17
17       18  Product A 2024-01-18  2024      1   18
18       19  Product A 2024-01-19  2024      1   19
19       20  Product A 2024-01-20  2024      1   20
29       30  Product B 2025-01-10  2025      1   10
30       31  Product C 2025-01-01  2025      1    1
31       32  Product C 2025-01-02  2025      1    2
32       33  Product C 2025-01-03  2025      1    3
33       34  Product B 2025-01-04  2025      1    4
34       35  Product B 2025-01-05  2025      1    5
35       36  Product A 2025-01-06  2025      1    6
36       37  Product A 2025-01-07  2025      1    7
37       38  Product A 2025-01-08  2025      1    8
38       39  Product A 2025-01-09  2025      1    9
39       40  Product B 2025-01-10  2025      1   10

### Задание 2: Категориальное кодирование
**Задача:** Преобразовать столбец категориальных данных в числовую форму, используя кодирование метки и одноточечное кодирование.

**Набор данных:** Данные об отзывах клиентов (`customer_feedback_data.csv`) со столбцами для идентификатора отзыва, возраста клиента, категории отзыва.

**Задачи:**

1. Загрузите набор данных в Pandas DataFrame.
2. Используйте кодирование меток для преобразования категории отзыва в числовые метки. 
То есть, необходимо заменить, например, значение positive на 1 и другие значения по аналогии.
3. Примените кодирование к Категории отзывов и добавьте новые столбцы в DataFrame.

In [15]:
import pandas as pd

df = pd.read_csv("customer_feedback_data.csv")
mapping = {"Negative": -1, "Neutral": 0, "Positive": 1 }
df["Feedback_Label"] = df["Feedback Category"].map(mapping)

df

    Feedback ID  Customer Age Feedback Category  Feedback_Label
0             1            20          Positive               1
1             2            35          Negative              -1
2             3            59          Positive               1
3             4            60          Positive               1
4             5            47           Neutral               0
5             6            32          Positive               1
6             7            30          Negative              -1
7             8            60          Negative              -1
8             9            22          Negative              -1
9            10            59          Negative              -1
10           11            29          Positive               1
11           12            43          Positive               1
12           13            21           Neutral               0
13           14            34          Negative              -1
14           15            68           Neutral               0
15           16            29          Positive               1
16           17            68          Positive               1
17           18            64          Negative              -1
18           19            48           Neutral               0
19           20            35          Positive               1

### Задание 3: Работа с пропущенными значениями
**Задача:** Определить и обработать пропущенные значения в наборе данных.

**Набор данных:** Данные о посещаемости сотрудников (`employee_attendance_data.csv`) со столбцами для идентификатора сотрудника, имени, отдела и дней отсутствия.

**Задачи:**

1. Загрузите набор данных в Pandas DataFrame.
2. Определите столбцы с недостающими значениями и рассчитайте процент недостающих данных для каждого столбца.
3. Заполните недостающие значения в столбце "Дни отсутствия" средним значением столбца.
4. Отбросьте строки, в которых отсутствует имя или отдел.

In [ ]:
import pandas as pd

df = pd.read_csv("employee_attendance_data.csv")
missing_pecent = df.isna().mean() * 100
missing_days_absent = df["Days Absent"].mean()

df["Days Absent"] = df["Days Absent"].fillna(missing_days_absent)
df = df.dropna(subset = ["Name" , "Department"])
print(df)

    Employee ID          Name Department  Days Absent
0             1      John Doe         IT          7.0
1             2  Alex Johnson        NaN          8.0
2             3      John Doe        NaN          3.0
3             4      John Doe         HR          8.0
4             5  Alex Johnson         IT          6.0
5             6    Jane Smith        NaN          NaN
6             7           NaN        NaN          NaN
7             8    Jane Smith        NaN          NaN
8             9      John Doe        NaN          NaN
9            10      John Doe         IT          NaN
10           11      John Doe      Sales          NaN
11           12      John Doe        NaN          6.0
12           13  Alex Johnson         IT          8.0
13           14    Jane Smith         IT          4.0
14           15      John Doe         IT          0.0
15           16           NaN         IT          8.0
16           17           NaN         HR          1.0
17           18    Jane Smith        NaN          7.0
18           19           NaN        NaN          8.0
19           20      John Doe      Sales          7.0

### Задание 4: Изменение типов данных
**Задание:** Изменить типы данных столбцов в наборе данных.

**Набор данных:** Данные инвентаризации продуктов (`product_inventory_data.csv`) со столбцами для идентификатора продукта, названия продукта, количества на складе и цены.

**Задачи:**

1. Загрузите набор данных в Pandas DataFrame.
2. Измените тип Stock Quantity на float, а тип Price - на integer.
3. Создайте новый столбец Stock Value как произведение Stock Quantity и Price.

### Задание 5: Манипулирование текстовыми данными
**Задача:** Манипулировать и очистить столбец текстовых данных.

**Набор данных:** Данные об онлайн отзывах (`online_reviews_data.csv`) со столбцами для ID отзыва, ID продукта, текста отзыва.

**Задачи:**

1. Загрузить набор данных в Pandas DataFrame.
2. Преобразовать текст отзыва в строчные буквы.
3. Удалите знаки препинания из текста отзыва.
4. Подсчитайте количество слов в каждом отзыве и добавьте его в новый столбец Word Count.